import Head from 'next/head'
import { useState } from 'react'
import Link from 'next/link'

const FORMSPREE_ID = 'YOUR_FORM_ID' // Replace with your Formspree ID

export default function Landing() {
  const [form, setForm] = useState({ name: '', email: '', phone: '', type: '', usecase: '', source: '' })
  const [status, setStatus] = useState('idle') // idle | loading | success | error
  const [count] = useState(7) // spots taken — update manually

  async function handleSubmit(e) {
    e.preventDefault()
    setStatus('loading')
    try {
      const res = await fetch(`https://formspree.io/f/${FORMSPREE_ID}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify(form),
      })
      if (res.ok) setStatus('success')
      else setStatus('error')
    } catch {
      setStatus('error')
    }
  }

  return (
    <>
      <Head>
        <title>Swor — AI Nepali Subtitles & Voiceover</title>
        <meta name="description" content="Generate Nepali subtitles and AI voiceovers in seconds. Nepal's first AI-powered Nepali language content tool. Free beta — only 20 spots." />
        <meta property="og:title" content="Swor — AI Nepali Subtitles & Voiceover" />
        <meta property="og:description" content="Nepal's first AI tool for Nepali subtitles and voiceover generation." />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet" />
      </Head>

      <style>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Plus Jakarta Sans', sans-serif; background: #fff; color: #0E0E16; }
        input, select, textarea { font-family: 'Plus Jakarta Sans', sans-serif; }
        a { text-decoration: none; color: inherit; }
      `}</style>

      {/* NAV */}
      <nav style={{ position: 'sticky', top: 0, zIndex: 100, background: 'rgba(255,255,255,0.92)', backdropFilter: 'blur(12px)', borderBottom: '1px solid #F0EDE8', padding: '0 24px', height: 60, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ width: 32, height: 32, borderRadius: 8, background: '#DC143C', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 16 }}>स्</div>
          <span style={{ fontSize: 18, fontWeight: 700, letterSpacing: -0.3 }}>Swor</span>
          <span style={{ fontSize: 11, color: '#999', borderLeft: '1px solid #E0DDD7', paddingLeft: 10, marginLeft: 2 }}>by MeroAD.ai</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <a href="#features" style={{ fontSize: 13, fontWeight: 500, color: '#555' }}>Features</a>
          <a href="#how-it-works" style={{ fontSize: 13, fontWeight: 500, color: '#555' }}>How it works</a>
          <Link href="/tool" style={{ fontSize: 13, fontWeight: 600, padding: '7px 16px', borderRadius: 8, border: '1.5px solid #DC143C', color: '#DC143C' }}>Access Tool →</Link>
        </div>
      </nav>

      {/* HERO */}
      <section style={{ background: 'linear-gradient(160deg, #0E0E16 0%, #1A0A1A 60%, #0E0E16 100%)', padding: '80px 24px 90px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', top: -60, left: '50%', transform: 'translateX(-50%)', width: 500, height: 500, borderRadius: '50%', background: 'radial-gradient(circle, rgba(220,20,60,0.15) 0%, transparent 70%)', pointerEvents: 'none' }} />
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(220,20,60,0.12)', border: '1px solid rgba(220,20,60,0.3)', borderRadius: 20, padding: '5px 14px', fontSize: 12, fontWeight: 600, color: '#FF6B8A', marginBottom: 24, letterSpacing: '0.04em' }}>
          🇳🇵 &nbsp;NEPAL'S FIRST AI NEPALI LANGUAGE TOOL
        </div>
        <h1 style={{ fontFamily: 'Instrument Serif, serif', fontSize: 56, fontWeight: 700, color: '#fff', lineHeight: 1.08, letterSpacing: -1, marginBottom: 20, maxWidth: 700, margin: '0 auto 20px' }}>
          Nepali Subtitles &amp; Voiceovers,<br /><em style={{ color: '#FF6B8A' }}>Generated by AI</em>
        </h1>
        <p style={{ fontSize: 18, color: 'rgba(255,255,255,0.6)', maxWidth: 520, margin: '0 auto 40px', lineHeight: 1.7 }}>
          Upload a video → get Nepali subtitles in seconds.<br />
          Type text → get a natural Nepali voiceover instantly.
        </p>
        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
          <a href="#apply" style={{ background: '#DC143C', color: '#fff', padding: '14px 28px', borderRadius: 10, fontSize: 15, fontWeight: 700, display: 'inline-flex', alignItems: 'center', gap: 8, boxShadow: '0 8px 32px rgba(220,20,60,0.35)' }}>
            Apply for Free Beta &nbsp;→
          </a>
          <Link href="/tool" style={{ background: 'rgba(255,255,255,0.08)', color: '#fff', border: '1px solid rgba(255,255,255,0.15)', padding: '14px 28px', borderRadius: 10, fontSize: 15, fontWeight: 600 }}>
            View the Tool
          </Link>
        </div>
        <div style={{ marginTop: 32, display: 'flex', gap: 32, justifyContent: 'center', flexWrap: 'wrap' }}>
          {[['51M+', 'Views on our AI content'], ['85K+', 'Followers on TikTok'], [String(20 - count) + ' left', 'Free beta spots'], ['Free', 'During beta period']].map(([n, l]) => (
            <div key={n} style={{ textAlign: 'center' }}>
              <div style={{ fontSize: 22, fontWeight: 700, color: '#fff' }}>{n}</div>
              <div style={{ fontSize: 11, color: 'rgba(255,255,255,0.4)', marginTop: 2 }}>{l}</div>
            </div>
          ))}
        </div>
      </section>

      {/* FEATURES */}
      <section id="features" style={{ padding: '80px 24px', background: '#FAFAF8' }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 48 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: '#DC143C', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 10 }}>What Swor does</div>
            <h2 style={{ fontFamily: 'Instrument Serif, serif', fontSize: 38, fontWeight: 700, letterSpacing: -0.5 }}>Two tools. One platform.</h2>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 }}>
            {[
              {
                icon: '🎬', color: '#DC143C', bg: '#FFF5F6',
                title: 'Nepali Subtitle Generator',
                desc: 'Upload any video or audio file. Our AI transcribes and generates accurate Nepali subtitles with timestamps — ready to import into CapCut, TikTok, or YouTube in one click.',
                points: ['Devanagari script support', 'Romanized Nepali option', 'Download as .SRT file', 'Works with MP4, MOV, MP3, WAV'],
              },
              {
                icon: '🎙️', color: '#6B3FBE', bg: '#F8F5FF',
                title: 'Nepali Voiceover Generator',
                desc: 'Type your Nepali text and choose from multiple AI voices. Get a natural-sounding Nepali voiceover downloaded as an MP3 — no recording studio needed.',
                points: ['5 Nepali voice options', 'Natural, expressive speech', 'Download as .MP3 file', 'Powered by ElevenLabs AI'],
              },
            ].map(f => (
              <div key={f.title} style={{ background: f.bg, border: `1.5px solid ${f.color}22`, borderRadius: 16, padding: '32px 28px' }}>
                <div style={{ fontSize: 36, marginBottom: 16 }}>{f.icon}</div>
                <h3 style={{ fontSize: 20, fontWeight: 700, color: '#0E0E16', marginBottom: 10 }}>{f.title}</h3>
                <p style={{ fontSize: 14, color: '#555', lineHeight: 1.7, marginBottom: 20 }}>{f.desc}</p>
                <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {f.points.map(p => (
                    <li key={p} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: '#333' }}>
                      <span style={{ color: f.color, fontWeight: 700 }}>✓</span> {p}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="how-it-works" style={{ padding: '80px 24px', background: '#fff' }}>
        <div style={{ maxWidth: 700, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: '#DC143C', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 10 }}>The process</div>
          <h2 style={{ fontFamily: 'Instrument Serif, serif', fontSize: 38, fontWeight: 700, letterSpacing: -0.5, marginBottom: 48 }}>How the beta works</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
            {[
              { n: '01', title: 'Apply below', desc: 'Fill in the short form. Tell us who you are and how you plan to use Swor. We review every application.' },
              { n: '02', title: 'Get approved', desc: 'We notify approved users within 24 hours via email with a private access link. Only 20 spots available.' },
              { n: '03', title: 'Use it free', desc: 'Access the full tool — subtitle generator and voiceover generator — completely free during the beta period with a generous character allowance.' },
            ].map((s, i) => (
              <div key={s.n} style={{ display: 'flex', gap: 20, textAlign: 'left', paddingBottom: 32, paddingTop: i === 0 ? 0 : 32, borderTop: i === 0 ? 'none' : '1px solid #F0EDE8' }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: '#DC143C', minWidth: 28, paddingTop: 4 }}>{s.n}</div>
                <div>
                  <div style={{ fontSize: 17, fontWeight: 700, marginBottom: 6 }}>{s.title}</div>
                  <div style={{ fontSize: 14, color: '#666', lineHeight: 1.7 }}>{s.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* APPLY FORM */}
      <section id="apply" style={{ padding: '80px 24px', background: 'linear-gradient(160deg, #0E0E16, #1A0A1A)' }}>
        <div style={{ maxWidth: 560, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 40 }}>
            <div style={{ display: 'inline-block', background: 'rgba(220,20,60,0.15)', border: '1px solid rgba(220,20,60,0.3)', borderRadius: 20, padding: '4px 14px', fontSize: 12, fontWeight: 700, color: '#FF6B8A', marginBottom: 16 }}>
              {20 - count} of 20 spots remaining
            </div>
            <h2 style={{ fontFamily: 'Instrument Serif, serif', fontSize: 36, color: '#fff', fontWeight: 700, marginBottom: 10 }}>Apply for free access</h2>
            <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', lineHeight: 1.7 }}>We review every application. Approved users get a private link within 24 hours.</p>
          </div>

          {status === 'success' ? (
            <div style={{ background: 'rgba(26,158,106,0.12)', border: '1.5px solid rgba(26,158,106,0.4)', borderRadius: 16, padding: '40px 32px', textAlign: 'center' }}>
              <div style={{ fontSize: 40, marginBottom: 16 }}>🙏</div>
              <div style={{ fontSize: 20, fontWeight: 700, color: '#fff', marginBottom: 8 }}>Application received!</div>
              <div style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', lineHeight: 1.7 }}>We'll review your application and send a decision to your email within 24 hours. Thank you for your interest in Swor.</div>
            </div>
          ) : (
            <form onSubmit={handleSubmit} style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 16, padding: '32px 28px', display: 'flex', flexDirection: 'column', gap: 16 }}>
              {[
                { id: 'name', label: 'Full Name *', placeholder: 'Your full name', type: 'text' },
                { id: 'email', label: 'Email Address *', placeholder: 'your@email.com', type: 'email' },
                { id: 'phone', label: 'WhatsApp / Phone', placeholder: '+977 98XXXXXXXX', type: 'tel' },
              ].map(f => (
                <div key={f.id}>
                  <label style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.5)', letterSpacing: '0.06em', textTransform: 'uppercase', display: 'block', marginBottom: 6 }}>{f.label}</label>
                  <input
                    type={f.type}
                    placeholder={f.placeholder}
                    required={f.label.includes('*')}
                    value={form[f.id]}
                    onChange={e => setForm({ ...form, [f.id]: e.target.value })}
                    style={{ width: '100%', padding: '11px 14px', borderRadius: 9, border: '1px solid rgba(255,255,255,0.12)', background: 'rgba(255,255,255,0.06)', color: '#fff', fontSize: 14, outline: 'none' }}
                  />
                </div>
              ))}

              <div>
                <label style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.5)', letterSpacing: '0.06em', textTransform: 'uppercase', display: 'block', marginBottom: 6 }}>I am a *</label>
                <select required value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} style={{ width: '100%', padding: '11px 14px', borderRadius: 9, border: '1px solid rgba(255,255,255,0.12)', background: '#1A1A2E', color: form.type ? '#fff' : 'rgba(255,255,255,0.4)', fontSize: 14, outline: 'none' }}>
                  <option value="">Select one</option>
                  <option value="creator">Content Creator (TikTok / YouTube / Instagram)</option>
                  <option value="business">Business / Brand</option>
                  <option value="marketer">Social Media Manager / Marketer</option>
                  <option value="ngo">NGO / Organization</option>
                  <option value="individual">Individual / Personal use</option>
                </select>
              </div>

              <div>
                <label style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.5)', letterSpacing: '0.06em', textTransform: 'uppercase', display: 'block', marginBottom: 6 }}>I will mainly use Swor for *</label>
                <select required value={form.usecase} onChange={e => setForm({ ...form, usecase: e.target.value })} style={{ width: '100%', padding: '11px 14px', borderRadius: 9, border: '1px solid rgba(255,255,255,0.12)', background: '#1A1A2E', color: form.usecase ? '#fff' : 'rgba(255,255,255,0.4)', fontSize: 14, outline: 'none' }}>
                  <option value="">Select one</option>
                  <option value="subtitles">Nepali subtitles for my videos</option>
                  <option value="voiceover">Nepali voiceover for content</option>
                  <option value="both">Both subtitles and voiceover</option>
                </select>
              </div>

              <div>
                <label style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.5)', letterSpacing: '0.06em', textTransform: 'uppercase', display: 'block', marginBottom: 6 }}>How did you hear about Swor?</label>
                <select value={form.source} onChange={e => setForm({ ...form, source: e.target.value })} style={{ width: '100%', padding: '11px 14px', borderRadius: 9, border: '1px solid rgba(255,255,255,0.12)', background: '#1A1A2E', color: form.source ? '#fff' : 'rgba(255,255,255,0.4)', fontSize: 14, outline: 'none' }}>
                  <option value="">Select one</option>
                  <option value="tiktok">TikTok</option>
                  <option value="instagram">Instagram</option>
                  <option value="linkedin">LinkedIn</option>
                  <option value="friend">Friend / Word of mouth</option>
                  <option value="google">Google Search</option>
                  <option value="other">Other</option>
                </select>
              </div>

              <button type="submit" disabled={status === 'loading'} style={{ background: status === 'loading' ? '#888' : '#DC143C', color: '#fff', border: 'none', padding: '14px', borderRadius: 10, fontSize: 15, fontWeight: 700, cursor: status === 'loading' ? 'not-allowed' : 'pointer', marginTop: 4, boxShadow: '0 6px 24px rgba(220,20,60,0.3)' }}>
                {status === 'loading' ? 'Submitting...' : 'Submit Application →'}
              </button>

              {status === 'error' && <div style={{ fontSize: 13, color: '#FF6B8A', textAlign: 'center' }}>Something went wrong. Please email us at AVASHSHRESTHAUSA@GMAIL.COM</div>}

              <p style={{ fontSize: 11, color: 'rgba(255,255,255,0.3)', textAlign: 'center', lineHeight: 1.6 }}>By applying you agree to our beta terms. We'll never spam you.</p>
            </form>
          )}
        </div>
      </section>

      {/* PAYMENT METHODS */}
      <section style={{ padding: '50px 24px', background: '#FAFAF8', borderTop: '1px solid #F0EDE8' }}>
        <div style={{ maxWidth: 700, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: '#999', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 20 }}>Accepted payment methods</div>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            {['eSewa', 'Khalti', 'IME Pay', 'Bank Transfer', 'PayPal'].map(p => (
              <span key={p} style={{ background: '#fff', border: '1px solid #E0DDD7', borderRadius: 8, padding: '8px 18px', fontSize: 13, fontWeight: 600, color: '#444' }}>{p}</span>
            ))}
          </div>
        </div>
      </section>

      {/* MEROAD.AI SERVICES */}
      <section style={{ padding: '60px 24px', background: '#0E0E16' }}>
        <div style={{ maxWidth: 700, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: 'rgba(255,255,255,0.3)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>Powered by</div>
          <div style={{ fontSize: 22, fontWeight: 700, color: '#fff', marginBottom: 12 }}>MeroAD.ai</div>
          <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', lineHeight: 1.8, maxWidth: 500, margin: '0 auto 28px' }}>
            We create AI-powered advertisements and commercials for Nepal brands. If you need full-scale AI content production for your business, we'd love to work with you.
          </p>
          <div style={{ display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap' }}>
            {[
              { label: 'Instagram', href: 'https://instagram.com/meroadai' },
              { label: 'Facebook', href: 'https://facebook.com/meroadai' },
              { label: 'TikTok', href: 'https://tiktok.com/@meroadai' },
              { label: 'DM for inquiries', href: 'mailto:AVASHSHRESTHAUSA@GMAIL.COM' },
            ].map(s => (
              <a key={s.label} href={s.href} target="_blank" rel="noreferrer" style={{ background: 'rgba(255,255,255,0.07)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 8, padding: '8px 18px', fontSize: 13, fontWeight: 600, color: 'rgba(255,255,255,0.7)' }}>
                {s.label}
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer style={{ padding: '24px', background: '#07070F', textAlign: 'center', fontSize: 12, color: 'rgba(255,255,255,0.25)' }}>
        © 2026 Swor by MeroAD.ai · Kathmandu, Nepal · AVASHSHRESTHAUSA@GMAIL.COM
      </footer>
    </>
  )
}
